import { SkillPost } from "@/types";

export const fakeProducts: SkillPost[] = [
  {
    id: "1",
    name: "Rahim Ali",
    campusId: "NSU-2023",
    teachingSkill: "Advanced React & Next.js",
    wantedSkills: ["UI/UX Design", "Figma"],
    thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=800&auto=format&fit=crop",
    description: "I can teach you modern frontend development in exchange for some solid design help for my startup idea.",
  },
  {
    id: "2",
    name: "Fatima Begum",
    campusId: "BRACU-01",
    teachingSkill: "IELTS Preparation (Band 8)",
    wantedSkills: ["Python Programming", "Data Sci"],
    thumbnailUrl: "https://images.unsplash.com/photo-1513258496099-48168024aec0?q=80&w=800&auto=format&fit=crop",
    description: "Looking for someone to teach me basic Python in exchange for spoken English and IELTS tips.",
  },
  {
    id: "3",
    name: "Sajid Hasan",
    campusId: "IUB-CS",
    teachingSkill: "Digital Marketing & SEO",
    wantedSkills: ["Video Editing", "Premiere Pro"],
    thumbnailUrl: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=800&auto=format&fit=crop",
    description: "I can help you rank your website dynamically.",
  },
  {
    id: "4",
    name: "Anika Tabassum",
    campusId: "DU-12",
    teachingSkill: "Graphic Design Basics",
    wantedSkills: ["Guitar Lessons"],
    thumbnailUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&auto=format&fit=crop",
    description: "I am a fine arts student. I can teach you photoshop if you have an acoustic guitar and can teach me to play.",
  },
  {
    id: "5",
    name: "Jihad Rahman",
    campusId: "AUST-ME",
    teachingSkill: "AutoCAD & 3D Modeling",
    wantedSkills: ["Calculus II", "Physics"],
    thumbnailUrl: "https://images.unsplash.com/photo-1525909002-1b05e0c869d8?q=80&w=800&auto=format&fit=crop",
    description: "Willing to do mechanical drafting tutoring for serious math/physics guidance before midterms.",
  },
  {
    id: "6",
    name: "Nusrat Jahan",
    campusId: "EWU-BBA",
    teachingSkill: "Accounting Principles",
    wantedSkills: ["Public Speaking"],
    thumbnailUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=800&auto=format&fit=crop",
    description: "Let's exchange accounting basics for confidence in public speaking.",
  },
  {
    id: "7",
    name: "Tariq Mahmud",
    campusId: "UIU-CSE",
    teachingSkill: "Data Structures in C++",
    wantedSkills: ["Photography", "Lightroom"],
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop",
    description: "If you have a DSLR and can teach me the basics, I will get you through your C++ course smoothly.",
  },
  {
    id: "8",
    name: "Samira Khan",
    campusId: "NSU-2022",
    teachingSkill: "French Language (A1-B1)",
    wantedSkills: ["Machine Learning", "AI"],
    thumbnailUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=800&auto=format&fit=crop",
    description: "Bonjour! I can help you with French grammar and speech, and in return I want to learn the basics of ML.",
  },
  {
    id: "9",
    name: "Ashiqur Rahman",
    campusId: "BUET-18",
    teachingSkill: "Advanced Algorithms",
    wantedSkills: ["Creative Writing"],
    thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop",
    description: "Competitive programming expert willing to teach advanced topics for help with my fictional story worldbuilding.",
  },
  {
    id: "10",
    name: "Mehazabien Alam",
    campusId: "BRACU-19",
    teachingSkill: "Photography & Lightroom",
    wantedSkills: ["Backend Dev", "Node.js"],
    thumbnailUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    description: "I will teach you how to properly color grade and use a camera for your learning roadmap.",
  },
  {
    id: "11",
    name: "Kabir Hossain",
    campusId: "IUT-20",
    teachingSkill: "Flutter Mobile App Dev",
    wantedSkills: ["UI/UX Prototyping"],
    thumbnailUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop",
    description: "Let's build a cross-platform app together while you teach me prototyping in Figma.",
  },
  {
    id: "12",
    name: "Sadia Islam",
    campusId: "DU-14",
    teachingSkill: "Content Writing",
    wantedSkills: ["Video Editing", "After Effects"],
    thumbnailUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=800&auto=format&fit=crop",
    description: "Need someone to teach me intense video editing for Youtube. I can write scripts and blogs for you.",
  },
  {
    id: "13",
    name: "Farhan Ahmed",
    campusId: "MIST-CE",
    teachingSkill: "Structural Design (ETABS)",
    wantedSkills: ["AutoCAD", "SketchUp"],
    thumbnailUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=800&auto=format&fit=crop",
    description: "Civil engineer giving lessons on building design, looking for some rendering tips.",
  },
  {
    id: "14",
    name: "Tahmina Akter",
    campusId: "NSU-18",
    teachingSkill: "Business Analytics",
    wantedSkills: ["Python", "Pandas"],
    thumbnailUrl: "https://images.unsplash.com/photo-1552058544-f2b08422138a?q=80&w=800&auto=format&fit=crop",
    description: "I am great with numbers and Excel. I want to transition to Python data analysis.",
  },
  {
    id: "15",
    name: "Rezwanul Haque",
    campusId: "AIUB-CIS",
    teachingSkill: "Cybersecurity Basics",
    wantedSkills: ["Cloud Sysadmin", "AWS"],
    thumbnailUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800&auto=format&fit=crop",
    description: "I can show you the ropes of web pentesting and ethical hacking. Seeking AWS cloud fundamentals.",
  },
  {
    id: "16",
    name: "Zara Sheikh",
    campusId: "BRACU-21",
    teachingSkill: "Japanese (JLPT N4)",
    wantedSkills: ["Piano Lessons"],
    thumbnailUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop",
    description: "I lived in Japan! I can teach basic communication. You teach me Piano keys.",
  },
  {
    id: "17",
    name: "Imran Khan",
    campusId: "UIU-EEE",
    teachingSkill: "Arduino & IoT",
    wantedSkills: ["Mobile App Dev"],
    thumbnailUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop",
    description: "Let's build smart home devices. I need an app developer to communicate with my hardware.",
  },
  {
    id: "18",
    name: "Tania Rahman",
    campusId: "DU-IB",
    teachingSkill: "Financial Modeling",
    wantedSkills: ["Public Speaking", "Debate"],
    thumbnailUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=800&auto=format&fit=crop",
    description: "Finance graduate. I can help you forecast revenue models anytime.",
  },
  {
    id: "19",
    name: "Emon Hasan",
    campusId: "IUB-CSE",
    teachingSkill: "Unity 3D Game Dev",
    wantedSkills: ["3D Animation", "Blender"],
    thumbnailUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=800&auto=format&fit=crop",
    description: "Making an indie game. I need pure 3D animation skills to exchange with programming logic.",
  },
  {
    id: "20",
    name: "Riya Sen",
    campusId: "EWU-CS",
    teachingSkill: "Python & Django",
    wantedSkills: ["React JS"],
    thumbnailUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    description: "I am a backend developer wanting to strengthen my frontend skills.",
  },
  {
    id: "21",
    name: "Nafis Iqbal",
    campusId: "SUST-CSE",
    teachingSkill: "System Design",
    wantedSkills: ["English Spoken"],
    thumbnailUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800&auto=format&fit=crop",
    description: "I've cracked major coding interviews, I need to improve my verbal communication.",
  },
  {
    id: "22",
    name: "Maliha Chowdhury",
    campusId: "NSU-PH",
    teachingSkill: "Public Health Research",
    wantedSkills: ["SPSS & R", "Data Visuals"],
    thumbnailUrl: "https://images.unsplash.com/photo-1502378735452-bc7d86632805?q=80&w=800&auto=format&fit=crop",
    description: "If you need advice on biomedical research design, I'm your guru.",
  },
  {
    id: "23",
    name: "Shohag Miah",
    campusId: "JU-Physics",
    teachingSkill: "Quantum Mechanics",
    wantedSkills: ["Web Development Basics"],
    thumbnailUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=800&auto=format&fit=crop",
    description: "Physics is fascinating. So is the web. Let's switch.",
  },
  {
    id: "24",
    name: "Lamia Hasan",
    campusId: "RU-Law",
    teachingSkill: "Contract Law Basics",
    wantedSkills: ["Personal Finance"],
    thumbnailUrl: "https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?q=80&w=800&auto=format&fit=crop",
    description: "Law student. I can review contracts and leases for you.",
  }
];
